// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinFormsApp2
{
    [Table("student")]
    public partial class student
    {
        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public string address { get; set; }
        public int? age { get; set; }
        public int? dept_id { get; set; }

        [ForeignKey("dept_id")]
        [InverseProperty("students")]
        public virtual department department { get; set; }
    }
}